import { Assistant } from "next/font/google";
import "./globals.css";
import Header from '@/components/Header'

const asistant = Assistant({ subsets: ["hebrew"],
weight: ["200", "300", "400", "500", "600", "700", "800"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={asistant.className}>
      <Header />

        {children}
        
        </body>
    </html>
  );
}
